Vagrant.configure("2") do |config|
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/focal64"
        web01.vm.network "private_network", ip: "192.168.33.81"
        web01.vm.hostname = "wordpress1"
    end

    config.vm.define "web02" do |web02|
        web02.vm.box = "ubuntu/focal64"
        web02.vm.network "private_network", ip: "192.168.33.82"
        web02.vm.hostname = "wordpress2"
    end

    config.vm.define "db01" do |db01|
        db01.vm.box = "centos/7"
        db01.vm.network "private_network", ip: "192.168.33.83"
        db01.vm.hostname = "dbserver"
        db01.vm.provision "shell", inline: <<-SHELL
            dnf install mariadb-server wget unzip -y 
            systemctl start mariadb
            systemctl enable mariadb
        SHELL
    end
end